### ISSUE TITLE
Feature: Add option to ignore multiple definitions of same id

### ISSUE THREAD

**Issue by sbreiler** [rubencosta/react-intl-gettext#3]
It would be nice to have an option for json2pot like **--ignore-multiple-ids** to avoid aborting this command, if an id is found more than once.

In my code, i use an id "Global__Continue":
`<button><FormattedMessage id='Global__Continue' defaultMessage='Continue' /></button>`

Its used in several files. Or do i miss a point of having unique ids?

(btw: thanks for your work)

**Comment by rubencosta** [comment]
Thanks @sbreiler 
May I ask why you have to define it in multiple files instead of defining it in one file and importing it in the places where you need it?

The React Intl message id is actually used as the gettext message context in the pot file therefore it does not support duplicates since message context is used to disambiguate possible duplicated messages.
